### ISSUE TITLE
Use luya docker php image

### ISSUE THREAD

**Issue by nadar** [denyadzi/varhansite#1]
Hi, i just saw this repo, maybe you might to replace the local luya php docker image with the one from dockerhub:

here you can see the diff from luya kickstarter: https://github.com/luyadev/luya-kickstarter/commit/e636cb5d0154c46cd585188350867f069be88c4b

If you like i will do a PR.

**Comment by denyadzi** [comment]
@nadar Hi 
Thank you for your attention. Yes, that would be much more convenient. 

I'll test it in my project -- I had one little issue in that local build I've forgotten to tell you. So, I'll connect back to you soon.

**Comment by nadar** [comment]
All right let me know.
